# file: roles/rundeck/tasks/main.yml
---
- name: install rundeck repo
  yum: name=http://repo.rundeck.org/latest.rpm state=present

- name: install rundeck
  yum: name=rundeck state=present

- name: start rundeck
  service: name=rundeckd enabled=true state=started
